input-files:
  - book/print-blanks.md
  - book/dust-jacket.md
output-file: "dust-jacket-us-trade.pdf"
from: markdown
to: pdf
dpi: 600
pdf-engine: prince
data-dir: "src"
template: "dust-jacket.html"
verbosity: WARNING # ERROR, WARNING, or INFO
