# docs https://pandoc.org/MANUAL.html#default-files
input-files:
  - book/04.md
  - book/07.md
output-file: "debord-guy-the-society-of-the-spectacle.epub"
metadata-files:
  - "book/metadata.yaml"
  - "book/metadata-epub.yaml"
from: markdown
to: epub
data-dir: "src"
template: "default.epub"
epub-chapter-level: 2
filters:
  - "src/filter-imagepath.js"
  - "src/filter-isbn.js"
  - "src/filter-date.lua"
verbosity: WARNING # ERROR, WARNING, or INFO
