# docs https://pandoc.org/MANUAL.html#default-files
input-files:
- chapters/cover.md
- chapters/colophon.md
- chapters/contents.md
- chapters/forward.md
- chapters/title.md
- chapters/preface.md
- chapters/01.md
- chapters/02.md
- chapters/03.md
- chapters/04.md
- chapters/05.md
- chapters/06.md
- chapters/07.md
- chapters/08.md
- chapters/09.md
- chapters/glossary.md
- chapters/bibliography.md
- chapters/actual-index.md
- chapters/authors.md
output-file: "docs/index.html"
metadata-files:
- "chapters/metadata.yaml"
from: markdown
file-scope: false
to: html5
data-dir: "src"
template: "default.html"
columns: 80
standalone: true
section-divs: true
verbosity: WARNING # ERROR, WARNING, or INFO
