# docs https://pandoc.org/MANUAL.html#default-files
input-files:
- book/half-title.md
- book/colophon.md
- book/contents.md
- book/foreword.md
- book/title.md
- book/preface.md
- book/01.md
- book/02.md
- book/03.md
- book/04.md
- book/05.md
- book/06.md
- book/07.md
- book/08.md
- book/09.md
- book/glossary.md
- book/bibliography.md
- book/authors.md
output-file: "docs/index.html"
metadata-files:
- "book/metadata.yaml"
- "book/metadata-website.yaml"
from: markdown
file-scope: false
to: html5
data-dir: "src"
template: "default.html"
filters:
  - "src/filter-isbn.js"
  - "src/filter-anchorlinks.js"
  - "src/filter-imagepath.js"
  - "src/filter-date.lua"
columns: 80
standalone: true
self-contained: true
section-divs: true
verbosity: WARNING # ERROR, WARNING, or INFO
