# docs https://pandoc.org/MANUAL.html#default-files
input-file: "book.md"
output-file: "book.pdf"
resource-path: ["images"] # needed for images linked in .md
metadata-files:
- "../chapters/metadata.yaml"
from: markdown
file-scope: false # Parse each file individually before combining for multifile documents. This will allow footnotes in different files with the same identifiers to work as expected. If this option is set, footnotes and links will not work across files.
to: pdf
standalone: true
pdf-engine: prince
data-dir: # A reference.odt, reference.docx, epub.css, templates, slidy, slideous, or s5 directory placed in this directory will override pandoc’s normal defaults.
abbreviations: # Specifies a custom abbreviations file, with abbreviations one to a line.
top-level-division: chapter # default | section | chapter | part
# log
verbosity: WARNING # ERROR, WARNING, or INFO
#log-file: log.json
