# docs https://pandoc.org/MANUAL.html#default-files
input-files:
- chapters/half-title.md
- chapters/title.md
- chapters/colophon.md
- chapters/contents.md
- chapters/preface.md
- chapters/01.md
- chapters/02.md
- chapters/03.md
- chapters/04.md
- chapters/05.md
- chapters/06.md
- chapters/07.md
- chapters/08.md
- chapters/09.md
- chapters/glossary.md
- chapters/bibliography.md
- chapters/actual-index.md
- chapters/authors.md
output-file: "dist/book.pdf"
metadata-files:
- "chapters/metadata.yaml"
from: markdown
to: pdf
dpi: 300
pdf-engine: prince
data-dir: "src"
template: "print.html"
verbosity: WARNING # ERROR, WARNING, or INFO
